// Historia clínica general — modelo oficial del Colegio Odontológico de la
// Provincia de Córdoba (Historia-Clinica-General.pdf, Fase 5.5).
//
// Dos páginas: los datos del profesional y del paciente, el cuestionario
// (con tenor de declaración jurada), la historia odontológica, el
// odontograma, el estado bucal, el diagnóstico, el plan, las
// observaciones y el consentimiento al tratamiento. Se firma en el
// sistema (TR-188): el paciente o su tutor y el profesional.
//
// Lo que el papel deja a criterio de quien lo llena se resolvió así:
//   - un SI/NO lleva `detalle` cuando lo que sigue pide aclarar el sí
//     ("cuál?", "de qué?"); cuando lo que sigue es otra pregunta ("está
//     controlado?", "se protege con alguna medicación?") es un campo aparte;
//     el renglón de la aclaración lleva solo el detalle (`{{campo:detalle}}`),
//     porque el sí o el no ya está marcado en su casilla;
//   - un hueco chico donde se responde marcando ("a la anestesia…..",
//     "Se puso hielo?……", "lengua?……") es una casilla de una opción
//     múltiple: lleva una X;
//   - un hueco que empieza a mitad de renglón y es demasiado angosto para
//     la primera palabra de una respuesta (menos de ~70 pt) no se usa: la
//     respuesta arranca en el renglón entero de abajo, porque el motor
//     cortaría esa palabra por letras;
//   - la firma del profesional no tiene renglón en el papel: va en el margen
//     libre de abajo, a la derecha, con su rótulo (única excepción al calco).
import type { Plantilla, Zona } from "../esquema";

const r2 = (n: number) => Math.round(n * 100) / 100;

// Las casillas del papel son el glifo ☐ de Wingdings 2 a 12 pt: un
// rectángulo de 6,5 × 8,9 pt cuyo lado izquierdo queda 0,9 pt después del
// origen del glifo y cuya base es la línea de base del renglón. La X va
// centrada adentro, a 8 pt.
function casilla(
  id: string,
  pagina: number,
  base: number,
  xGlifo: number,
  texto: string,
): Zona {
  return {
    id,
    pagina,
    x: r2(xGlifo + 0.9),
    y: r2(base - 1.6),
    ancho: 6.5,
    tamano: 8,
    alinear: "centro",
    vacio: "—",
    texto,
  };
}

/** Las dos casillas de un SI/NO, en el renglón de su pregunta. */
function siNo(
  campo: string,
  pagina: number,
  base: number,
  xSi: number,
  xNo: number,
): Zona[] {
  return [
    casilla(`${campo}_si`, pagina, base, xSi, `{{${campo}=si}}`),
    casilla(`${campo}_no`, pagina, base, xNo, `{{${campo}=no}}`),
  ];
}

// Las dos columnas del cuestionario tienen sus casillas en x fijas.
const izquierda = (campo: string, pagina: number, base: number) =>
  pagina === 1
    ? siNo(campo, 1, base, 244.5, 276.3)
    : siNo(campo, 2, base, 253.5, 285.3);
const derecha = (campo: string, base: number) =>
  siNo(campo, 1, base, 517.0, 548.8);
const derechaAncha = (campo: string, pagina: number, base: number) =>
  siNo(campo, pagina, base, 526.0, 557.8);

/** Una X en un hueco de puntos ("a la anestesia…..", "lengua?……"). */
function enHueco(
  id: string,
  pagina: number,
  base: number,
  x: number,
  ancho: number,
  texto: string,
): Zona {
  return {
    id,
    pagina,
    x,
    y: r2(base - 1.2),
    ancho,
    tamano: 8,
    alinear: "centro",
    vacio: "—",
    texto,
  };
}

export const historiaClinicaGeneral: Plantilla = {
  id: "historia-clinica-general",
  version: 1,
  nombre: "Historia clínica general",
  tipo: "historia_clinica",
  descripcion:
    "Datos del paciente, cuestionario de salud con tenor de declaración jurada, historia odontológica, odontograma, diagnóstico, plan de tratamiento y consentimiento.",
  fuente: {
    nombre: "Colegio Odontológico de la Provincia de Córdoba",
    url: "https://colodontcba.org.ar/wp-content/uploads/Docs/Historia-Clinica-General.pdf",
  },
  secciones: [
    {
      id: "encabezado",
      titulo: "Lugar y profesional",
      campos: [
        {
          tipo: "texto",
          id: "lugar",
          etiqueta: "Lugar",
          requerido: true,
          precarga: "clinica.ciudad",
        },
        {
          tipo: "texto",
          id: "odontologo",
          etiqueta: "Odontólogo",
          requerido: true,
          precarga: "profesional.nombreCompleto",
          bloqueado: true,
        },
        {
          tipo: "texto",
          id: "matricula",
          etiqueta: "Nº de matrícula",
          requerido: true,
          precarga: "profesional.matriculaNumero",
          bloqueado: true,
        },
      ],
    },
    {
      id: "paciente",
      titulo: "Paciente",
      campos: [
        {
          tipo: "texto",
          id: "paciente_nombre",
          etiqueta: "Paciente",
          requerido: true,
          precarga: "paciente.nombreCompleto",
        },
        {
          tipo: "texto",
          id: "afiliado",
          etiqueta: "Nº de afiliado",
          precarga: "paciente.obraSocialAfiliado",
        },
        {
          tipo: "texto",
          id: "obra_social",
          etiqueta: "Obra social",
          precarga: "paciente.obraSocial",
        },
        {
          tipo: "fecha",
          id: "fecha_nacimiento",
          etiqueta: "Fecha de nacimiento",
          precarga: "paciente.fechaNacimiento",
        },
        {
          tipo: "numero",
          id: "edad",
          etiqueta: "Edad",
          unidad: "años",
          min: 0,
          max: 120,
        },
        { tipo: "texto", id: "estado_civil", etiqueta: "Estado civil" },
        { tipo: "texto", id: "nacionalidad", etiqueta: "Nacionalidad" },
        {
          tipo: "texto",
          id: "dni",
          etiqueta: "Nº de documento",
          precarga: "paciente.dni",
        },
        { tipo: "texto", id: "telefono", etiqueta: "Teléfono" },
        // El teléfono de la ficha es el del WhatsApp de los turnos: un celular.
        {
          tipo: "texto",
          id: "celular",
          etiqueta: "Celular",
          precarga: "paciente.telefono",
        },
        {
          tipo: "texto",
          id: "domicilio",
          etiqueta: "Domicilio (calle, número, barrio, localidad)",
          precarga: "paciente.domicilio",
        },
        { tipo: "texto", id: "profesion", etiqueta: "Profesión o actividad" },
        { tipo: "texto", id: "titular", etiqueta: "Titular de la obra social" },
        { tipo: "texto", id: "lugar_trabajo", etiqueta: "Lugar de trabajo" },
        { tipo: "texto", id: "jerarquia", etiqueta: "Jerarquía" },
      ],
    },
    {
      id: "familia",
      titulo: "Antecedentes familiares",
      campos: [
        { tipo: "si_no", id: "padre_vive", etiqueta: "¿Padre con vida?" },
        {
          tipo: "texto_largo",
          id: "padre_enfermedad",
          etiqueta: "Enfermedad que padece o padeció el padre",
        },
        { tipo: "si_no", id: "madre_vive", etiqueta: "¿Madre con vida?" },
        {
          tipo: "texto_largo",
          id: "madre_enfermedad",
          etiqueta: "Enfermedad que padece o padeció la madre",
        },
        { tipo: "si_no", id: "hermanos", etiqueta: "¿Hermanos?" },
        { tipo: "texto", id: "hermanos_sanos", etiqueta: "¿Sanos?" },
      ],
    },
    {
      id: "salud",
      titulo: "Salud y medicación",
      campos: [
        {
          tipo: "si_no",
          id: "enfermedad",
          etiqueta: "¿Sufre de alguna enfermedad?",
          detalle: { etiqueta: "¿De qué?", cuando: "si" },
        },
        {
          tipo: "si_no",
          id: "tratamiento_medico",
          etiqueta: "¿Hace algún tratamiento médico?",
          detalle: { etiqueta: "¿Cuál?", cuando: "si" },
        },
        {
          tipo: "texto_largo",
          id: "medicamentos_habituales",
          etiqueta: "¿Qué medicamentos consume habitualmente?",
        },
        {
          tipo: "texto_largo",
          id: "medicamentos_5_anios",
          etiqueta: "¿Qué medicamentos ha consumido en los últimos 5 años?",
        },
        { tipo: "si_no", id: "deporte", etiqueta: "¿Realiza algún deporte?" },
        {
          tipo: "si_no",
          id: "deporte_malestar",
          etiqueta: "¿Nota algún malestar al realizarlo?",
        },
      ],
    },
    {
      id: "alergias",
      titulo: "Alergias y cicatrización",
      campos: [
        {
          tipo: "si_no",
          id: "alergico",
          etiqueta: "¿Es alérgico a alguna droga?",
        },
        {
          tipo: "opcion_multiple",
          id: "alergias",
          etiqueta: "¿A cuáles?",
          opciones: [
            { valor: "anestesia", etiqueta: "A la anestesia" },
            { valor: "penicilina", etiqueta: "A la penicilina" },
          ],
        },
        { tipo: "texto", id: "alergias_otras", etiqueta: "Otras drogas" },
        {
          tipo: "texto_largo",
          id: "cicatrizacion",
          etiqueta:
            "Cuando le sacan una muela o se lastima, ¿cicatriza bien? ¿Sangra mucho?",
        },
        {
          tipo: "si_no",
          id: "colageno",
          etiqueta: "¿Tiene problema de colágeno (hiperlaxitud)?",
        },
        {
          tipo: "si_no",
          id: "fiebre_reumatica",
          etiqueta: "¿Antecedentes de fiebre reumática?",
        },
        {
          tipo: "texto",
          id: "fiebre_reumatica_proteccion",
          etiqueta: "¿Se protege con alguna medicación?",
        },
      ],
    },
    {
      id: "enfermedades",
      titulo: "Enfermedades",
      campos: [
        { tipo: "si_no", id: "diabetico", etiqueta: "¿Es diabético?" },
        // Una opción y no un SI/NO: el hueco del papel (16 pt) lleva la
        // respuesta escrita, y un SI/NO se escribe con su aclaración.
        {
          tipo: "opcion_unica",
          id: "diabetes_controlada",
          etiqueta: "¿Está controlado?",
          opciones: [
            { valor: "si", etiqueta: "Sí" },
            { valor: "no", etiqueta: "No" },
          ],
        },
        { tipo: "texto", id: "diabetes_con_que", etiqueta: "¿Con qué?" },
        {
          tipo: "si_no",
          id: "cardiaco",
          etiqueta: "¿Tiene algún problema cardíaco?",
          detalle: { etiqueta: "¿Cuál?", cuando: "si" },
        },
        {
          tipo: "si_no",
          id: "aspirina",
          etiqueta: "¿Toma seguido aspirina o anticoagulantes?",
          detalle: { etiqueta: "¿Con qué frecuencia?", cuando: "si" },
        },
        { tipo: "si_no", id: "presion_alta", etiqueta: "¿Tiene presión alta?" },
        { tipo: "si_no", id: "chagas", etiqueta: "¿Chagas?" },
        {
          tipo: "texto",
          id: "chagas_tratamiento",
          etiqueta: "¿Está en tratamiento?",
        },
        { tipo: "si_no", id: "renales", etiqueta: "¿Tiene problemas renales?" },
        { tipo: "si_no", id: "ulcera", etiqueta: "¿Úlcera gástrica?" },
        { tipo: "si_no", id: "hepatitis", etiqueta: "¿Tuvo hepatitis?" },
        {
          tipo: "opcion_multiple",
          id: "hepatitis_tipo",
          etiqueta: "¿De qué tipo?",
          opciones: [
            { valor: "a", etiqueta: "A" },
            { valor: "b", etiqueta: "B" },
            { valor: "c", etiqueta: "C" },
          ],
        },
        {
          tipo: "si_no",
          id: "hepatico",
          etiqueta: "¿Tiene algún problema hepático?",
          detalle: { etiqueta: "¿Cuál?", cuando: "si" },
        },
        { tipo: "si_no", id: "convulsiones", etiqueta: "¿Tuvo convulsiones?" },
        {
          tipo: "si_no",
          id: "epileptico",
          etiqueta: "¿Es epiléptico?",
          detalle: { etiqueta: "Medicación que toma", cuando: "si" },
        },
        {
          tipo: "si_no",
          id: "sifilis",
          etiqueta: "¿Ha tenido sífilis o gonorrea?",
        },
        {
          tipo: "si_no",
          id: "infecto",
          etiqueta: "¿Otra enfermedad infecto-contagiosa?",
        },
        {
          tipo: "si_no",
          id: "transfusiones",
          etiqueta: "¿Tuvo transfusiones?",
        },
        {
          tipo: "si_no",
          id: "operado",
          etiqueta: "¿Fue operado alguna vez?",
          detalle: { etiqueta: "¿De qué?", cuando: "si" },
        },
        { tipo: "texto", id: "operado_cuando", etiqueta: "¿Cuándo?" },
        {
          tipo: "si_no",
          id: "respiratorio",
          etiqueta: "¿Tiene algún problema respiratorio?",
          detalle: { etiqueta: "¿Cuál?", cuando: "si" },
        },
        { tipo: "si_no", id: "fuma", etiqueta: "¿Fuma?" },
        {
          tipo: "si_no",
          id: "embarazada",
          etiqueta: "¿Está embarazada?",
          detalle: { etiqueta: "¿De cuántos meses?", cuando: "si" },
        },
        {
          tipo: "si_no",
          id: "otra_enfermedad",
          etiqueta:
            "¿Hay alguna otra enfermedad o recomendación de su médico que quiera dejar constancia?",
          detalle: { etiqueta: "¿Cuál?", cuando: "si" },
        },
      ],
    },
    {
      id: "medico",
      titulo: "Médico y derivación",
      campos: [
        {
          tipo: "texto",
          id: "homeopatia",
          etiqueta:
            "¿Realiza algún tratamiento homeopático, acupuntura u otros?",
        },
        { tipo: "texto", id: "medico_clinico", etiqueta: "Médico clínico" },
        {
          tipo: "texto",
          id: "derivacion",
          etiqueta: "Clínica u hospital en caso de hacer falta derivación",
        },
      ],
    },
    {
      id: "consulta",
      titulo: "Consulta y dolor",
      campos: [
        {
          tipo: "texto_largo",
          id: "motivo_consulta",
          etiqueta: "¿Por qué asistió a la consulta?",
        },
        {
          tipo: "si_no",
          id: "consulto_otro",
          etiqueta: "¿Consultó antes con algún otro profesional?",
        },
        {
          tipo: "si_no",
          id: "tomo_medicamento",
          etiqueta: "¿Tomó algún medicamento?",
          detalle: { etiqueta: "Nombre de los medicamentos", cuando: "si" },
        },
        { tipo: "texto", id: "medicamento_desde", etiqueta: "¿Desde cuándo?" },
        {
          tipo: "si_no",
          id: "medicamento_resultados",
          etiqueta: "¿Obtuvo resultados?",
        },
        { tipo: "si_no", id: "dolor", etiqueta: "¿Ha tenido dolor?" },
        {
          tipo: "opcion_multiple",
          id: "dolor_tipo",
          etiqueta: "¿De qué tipo?",
          opciones: [
            { valor: "suave", etiqueta: "Suave" },
            { valor: "moderado", etiqueta: "Moderado" },
            { valor: "intenso", etiqueta: "Intenso" },
            { valor: "temporario", etiqueta: "Temporario" },
            { valor: "intermitente", etiqueta: "Intermitente" },
            { valor: "continuo", etiqueta: "Continuo" },
            { valor: "espontaneo", etiqueta: "Espontáneo" },
            { valor: "provocado", etiqueta: "Provocado" },
            { valor: "al_frio", etiqueta: "Al frío" },
            { valor: "al_calor", etiqueta: "Al calor" },
            { valor: "localizado", etiqueta: "Localizado" },
            { valor: "irradiado", etiqueta: "Irradiado" },
          ],
        },
        { tipo: "texto", id: "dolor_donde", etiqueta: "Localizado: ¿dónde?" },
        {
          tipo: "texto",
          id: "dolor_hacia_donde",
          etiqueta: "Irradiado: ¿hacia dónde?",
        },
        {
          tipo: "texto_largo",
          id: "dolor_calma",
          etiqueta: "¿Puede calmarlo con algo?",
        },
      ],
    },
    {
      id: "golpes",
      titulo: "Golpes y fracturas",
      campos: [
        {
          tipo: "si_no",
          id: "golpe",
          etiqueta: "¿Sufrió algún golpe en los dientes?",
        },
        { tipo: "texto", id: "golpe_cuando", etiqueta: "¿Cuándo?" },
        {
          tipo: "texto_largo",
          id: "golpe_como",
          etiqueta: "¿Cómo se produjo?",
        },
        {
          tipo: "si_no",
          id: "fractura",
          etiqueta: "¿Se le fracturó algún diente?",
          detalle: { etiqueta: "¿Cuál?", cuando: "si" },
        },
        {
          tipo: "texto_largo",
          id: "fractura_tratamiento",
          etiqueta: "¿Recibió algún tratamiento?",
        },
      ],
    },
    {
      id: "funciones",
      titulo: "Dificultades",
      campos: [
        {
          tipo: "texto",
          id: "dificultad_hablar",
          etiqueta: "¿Tiene dificultad para hablar?",
        },
        {
          tipo: "texto",
          id: "dificultad_masticar",
          etiqueta: "¿Para masticar?",
        },
        {
          tipo: "texto",
          id: "dificultad_abrir",
          etiqueta: "¿Para abrir la boca?",
        },
        {
          tipo: "texto",
          id: "dificultad_tragar",
          etiqueta: "¿Para tragar los alimentos?",
        },
      ],
    },
    {
      id: "lesiones",
      titulo: "Lesiones",
      campos: [
        {
          tipo: "opcion_multiple",
          id: "anormal_en",
          etiqueta: "¿Ha observado algo anormal en…?",
          opciones: [
            { valor: "labios", etiqueta: "Labios" },
            { valor: "lengua", etiqueta: "Lengua" },
            { valor: "paladar", etiqueta: "Paladar" },
            { valor: "piso_de_boca", etiqueta: "Piso de boca" },
            { valor: "carrillos", etiqueta: "Carrillos" },
            { valor: "rebordes", etiqueta: "Rebordes" },
            { valor: "trigono", etiqueta: "Trígono" },
            { valor: "retromolar", etiqueta: "Retromolar" },
          ],
        },
        { tipo: "si_no", id: "manchas", etiqueta: "¿Manchas?" },
        {
          tipo: "si_no",
          id: "abultamiento",
          etiqueta: "¿Abultamiento de los tejidos?",
        },
        { tipo: "si_no", id: "ulceraciones", etiqueta: "¿Ulceraciones?" },
        { tipo: "si_no", id: "ampollas", etiqueta: "¿Ampollas?" },
        {
          tipo: "texto_largo",
          id: "lesiones_otras",
          etiqueta: "Otras lesiones",
        },
        {
          tipo: "si_no",
          id: "encias_sangran",
          etiqueta: "¿Le sangran las encías?",
          detalle: { etiqueta: "¿Cuándo?", cuando: "si" },
        },
      ],
    },
    {
      id: "signos",
      titulo: "Otros signos e higiene",
      campos: [
        {
          tipo: "si_no",
          id: "pus",
          etiqueta: "¿Sale pus de algún lugar de su boca?",
          detalle: { etiqueta: "¿De dónde?", cuando: "si" },
        },
        {
          tipo: "si_no",
          id: "movilidad",
          etiqueta: "¿Tiene movilidad en sus dientes?",
        },
        {
          tipo: "texto",
          id: "dientes_altos",
          etiqueta: "¿Al morder siente altos los dientes?",
        },
        {
          tipo: "si_no",
          id: "cara_hinchada",
          etiqueta: "¿Ha tenido la cara hinchada?",
        },
        {
          tipo: "opcion_multiple",
          id: "hinchazon_aplico",
          etiqueta: "¿Se puso…?",
          opciones: [
            { valor: "hielo", etiqueta: "Hielo" },
            { valor: "calor", etiqueta: "Calor" },
          ],
        },
        { tipo: "texto", id: "hinchazon_otros", etiqueta: "¿Otros?" },
        {
          tipo: "texto",
          id: "momentos_azucar",
          etiqueta: "Momentos de azúcar diario",
        },
        { tipo: "texto", id: "indice_placa", etiqueta: "Índice de placa" },
        {
          tipo: "opcion_unica",
          id: "higiene",
          etiqueta: "Estado de la higiene bucal",
          opciones: [
            { valor: "muy_bueno", etiqueta: "Muy bueno" },
            { valor: "bueno", etiqueta: "Bueno" },
            { valor: "deficiente", etiqueta: "Deficiente" },
            { valor: "malo", etiqueta: "Malo" },
          ],
        },
      ],
    },
    {
      id: "odontograma",
      titulo: "Odontograma",
      campos: [
        {
          tipo: "odontograma",
          id: "odontograma",
          etiqueta: "Odontograma",
          leyenda: "general",
          denticion: "ambas",
          existentes: true,
        },
      ],
    },
    {
      id: "estado_bucal",
      titulo: "Estado bucal general",
      campos: [
        { tipo: "si_no", id: "sarro", etiqueta: "¿Presencia de sarro?" },
        {
          tipo: "si_no",
          id: "periodontal",
          etiqueta: "¿Enfermedad periodontal?",
        },
      ],
    },
    {
      id: "diagnostico",
      titulo: "Diagnóstico y plan",
      campos: [
        {
          tipo: "texto_largo",
          id: "diagnostico",
          etiqueta: "Diagnóstico presuntivo",
        },
        {
          tipo: "numero",
          id: "diagnostico_anexo",
          etiqueta: "Continúa en anexo Nº",
          min: 1,
          max: 999,
        },
        {
          tipo: "fecha",
          id: "plan_fecha",
          etiqueta: "Fecha del plan de tratamiento",
        },
        { tipo: "texto_largo", id: "plan", etiqueta: "Plan de tratamiento" },
        {
          tipo: "numero",
          id: "plan_anexo",
          etiqueta: "Continúa en anexo Nº",
          min: 1,
          max: 999,
        },
        { tipo: "texto_largo", id: "observaciones", etiqueta: "Observaciones" },
        {
          tipo: "numero",
          id: "observaciones_anexo",
          etiqueta: "Continúa en anexo Nº",
          min: 1,
          max: 999,
        },
      ],
    },
    {
      id: "consentimiento",
      titulo: "Quien suscribe",
      campos: [
        // Precargados del paciente, pero editables: puede suscribir su tutor.
        {
          tipo: "texto",
          id: "suscribe_nombre",
          etiqueta: "Nombre y apellido",
          requerido: true,
          precarga: "paciente.nombreCompleto",
        },
        {
          tipo: "texto",
          id: "suscribe_dni",
          etiqueta: "DNI",
          requerido: true,
          precarga: "paciente.dni",
        },
        {
          tipo: "texto",
          id: "suscribe_domicilio",
          etiqueta: "Domicilio",
          precarga: "paciente.domicilio",
        },
      ],
    },
  ],
  cuerpo: [
    { t: "titulo", texto: "Historia clínica general" },
    { t: "parrafo", texto: "Lugar: {{lugar}}. Fecha: {{sistema.fecha}}." },
    {
      t: "parrafo",
      texto: "Odontólogo: {{odontologo}}. Nº de matrícula: {{matricula}}.",
    },
    {
      t: "parrafo",
      texto: "Paciente: {{paciente_nombre}}. Nº de afiliado: {{afiliado}}.",
    },
    {
      t: "parrafo",
      texto:
        "Obra social: {{obra_social}}. Fecha de nacimiento: {{fecha_nacimiento}}. Tel.: {{telefono}}. Edad: {{edad}}. Estado civil: {{estado_civil}}. Nacionalidad: {{nacionalidad}}. Nº de documento: {{dni}}. Cel.: {{celular}}.",
    },
    {
      t: "parrafo",
      texto: "Domicilio (calle, núm., barrio, localidad): {{domicilio}}.",
    },
    {
      t: "parrafo",
      texto:
        "Profesión/Actividad: {{profesion}}. Titular: {{titular}}. Lugar de trabajo: {{lugar_trabajo}}. Jerarquía: {{jerarquia}}.",
    },
    {
      t: "subtitulo",
      texto: "Este cuestionario tiene el tenor de una “Declaración Jurada”",
    },
    {
      t: "lista",
      items: [
        "¿Padre con vida? {{padre_vive}}. Enfermedad que padece o padeció: {{padre_enfermedad}}.",
        "¿Madre con vida? {{madre_vive}}. Enfermedad que padece o padeció: {{madre_enfermedad}}.",
        "¿Hermanos? {{hermanos}}. ¿Sanos? {{hermanos_sanos}}.",
        "¿Sufre de alguna enfermedad? {{enfermedad}}.",
        "¿Hace algún tratamiento médico? {{tratamiento_medico}}.",
        "¿Qué medicamentos consume habitualmente? {{medicamentos_habituales}}.",
        "¿Qué medicamentos ha consumido en los últimos 5 años? {{medicamentos_5_anios}}.",
        "¿Realiza algún deporte? {{deporte}}. ¿Nota algún malestar al realizarlo? {{deporte_malestar}}.",
        "¿Es alérgico a alguna droga? {{alergico}}. ¿A cuáles? {{alergias}}. Otras: {{alergias_otras}}.",
        "Cuando le sacan una muela o se lastima, ¿cicatriza bien? ¿Sangra mucho? {{cicatrizacion}}.",
        "¿Tiene problema de colágeno (hiperlaxitud)? {{colageno}}.",
        "¿Antecedentes de fiebre reumática? {{fiebre_reumatica}}. ¿Se protege con alguna medicación? {{fiebre_reumatica_proteccion}}.",
        "¿Es diabético? {{diabetico}}. ¿Está controlado? {{diabetes_controlada}}. ¿Con qué? {{diabetes_con_que}}.",
        "¿Tiene algún problema cardíaco? {{cardiaco}}.",
        "¿Toma seguido aspirina y/o anticoagulante? {{aspirina}}.",
        "¿Tiene presión alta? {{presion_alta}}.",
        "¿Chagas? {{chagas}}. ¿Está en tratamiento? {{chagas_tratamiento}}.",
        "¿Tiene problemas renales? {{renales}}.",
        "¿Úlcera gástrica? {{ulcera}}.",
        "¿Tuvo hepatitis? {{hepatitis}}. ¿De qué tipo? {{hepatitis_tipo}}.",
        "¿Tiene algún problema hepático? {{hepatico}}.",
        "¿Tuvo convulsiones? {{convulsiones}}.",
        "¿Es epiléptico? {{epileptico}}.",
        "¿Ha tenido sífilis o gonorrea? {{sifilis}}.",
        "¿Otra enfermedad infecto-contagiosa? {{infecto}}.",
        "¿Tuvo transfusiones? {{transfusiones}}.",
        "¿Fue operado alguna vez? {{operado}}. ¿Cuándo? {{operado_cuando}}.",
        "¿Tiene algún problema respiratorio? {{respiratorio}}.",
        "¿Fuma? {{fuma}}.",
        "¿Está embarazada? {{embarazada}}.",
        "¿Hay alguna otra enfermedad o recomendación de su médico que quiera dejar constancia? {{otra_enfermedad}}.",
        "¿Realiza algún tipo de tratamiento homeopático, acupuntura, otros? {{homeopatia}}.",
        "Médico clínico: {{medico_clinico}}.",
        "Clínica/Hospital en caso de hacer falta derivación: {{derivacion}}.",
      ],
    },
    { t: "subtitulo", texto: "Historia clínica odontológica" },
    {
      t: "lista",
      items: [
        "¿Por qué asistió a la consulta? {{motivo_consulta}}.",
        "¿Consultó antes con algún otro profesional? {{consulto_otro}}.",
        "¿Tomó algún medicamento? {{tomo_medicamento}}. ¿Desde cuándo? {{medicamento_desde}}. ¿Obtuvo resultados? {{medicamento_resultados}}.",
        "¿Ha tenido dolor? {{dolor}}. ¿De qué tipo? {{dolor_tipo}}. Localizado, ¿dónde? {{dolor_donde}}. Irradiado, ¿hacia dónde? {{dolor_hacia_donde}}.",
        "¿Puede calmarlo con algo? {{dolor_calma}}.",
        "¿Sufrió algún golpe en los dientes? {{golpe}}. ¿Cuándo? {{golpe_cuando}}. ¿Cómo se produjo? {{golpe_como}}.",
        "¿Se le fracturó algún diente? {{fractura}}. ¿Recibió algún tratamiento? {{fractura_tratamiento}}.",
        "¿Tiene dificultad para hablar? {{dificultad_hablar}}. ¿Para masticar? {{dificultad_masticar}}. ¿Para abrir la boca? {{dificultad_abrir}}. ¿Para tragar los alimentos? {{dificultad_tragar}}.",
        "¿Ha observado algo anormal en los labios, lengua, paladar, piso de boca, carrillos, rebordes, trígono o retromolar? {{anormal_en}}.",
        "¿Qué tipo de lesiones presenta? Manchas: {{manchas}}. Abultamiento de los tejidos: {{abultamiento}}. Ulceraciones: {{ulceraciones}}. Ampollas: {{ampollas}}. Otros: {{lesiones_otras}}.",
        "¿Le sangran las encías? {{encias_sangran}}.",
        "¿Sale pus de algún lugar de su boca? {{pus}}.",
        "¿Tiene movilidad en sus dientes? {{movilidad}}. ¿Al morder siente altos los dientes? {{dientes_altos}}.",
        "¿Ha tenido la cara hinchada? {{cara_hinchada}}. ¿Se puso hielo o calor? {{hinchazon_aplico}}. ¿Otros? {{hinchazon_otros}}.",
        "Momentos de azúcar diario: {{momentos_azucar}}. Índice de placa: {{indice_placa}}.",
        "Estado de la higiene bucal: {{higiene}}.",
      ],
    },
    {
      t: "parrafo",
      texto:
        "Declaro que he contestado todas las preguntas con honestidad y según mi conocimiento. Asimismo, he sido informado que los datos suministrados quedan reservados en la presente Historia Clínica y amparados en secreto profesional.",
    },
    { t: "campo", campo: "odontograma" },
    {
      t: "parrafo",
      texto:
        "Estado bucal general: presencia de sarro: {{sarro}}. Enfermedad periodontal: {{periodontal}}.",
    },
    { t: "campo", campo: "diagnostico" },
    { t: "parrafo", texto: "Continúa en anexo Nº {{diagnostico_anexo}}." },
    { t: "parrafo", texto: "Plan de tratamiento. Fecha: {{plan_fecha}}." },
    { t: "campo", campo: "plan" },
    { t: "parrafo", texto: "Continúa en anexo Nº {{plan_anexo}}." },
    { t: "campo", campo: "observaciones" },
    { t: "parrafo", texto: "Continúa en anexo Nº {{observaciones_anexo}}." },
    {
      t: "parrafo",
      texto:
        "He comprendido todas las explicaciones que se me han facilitado en el lenguaje claro y sencillo, he podido realizar todas las observaciones y se me han aclarado todas las dudas; por lo que estoy completamente de acuerdo con el tratamiento que se me va a realizar.",
    },
    {
      t: "parrafo",
      texto:
        "El/la que suscribe {{suscribe_nombre}}, DNI Nº {{suscribe_dni}}, con domicilio en calle {{suscribe_domicilio}}, otorgo mi consentimiento para realizar el tratamiento necesario para rehabilitar mi salud bucodental propuesta por el/la Dr/a {{odontologo}}, MP {{matricula}}.",
    },
    { t: "firmas" },
  ],
  firmas: [
    { rol: "paciente", etiqueta: "Paciente o tutor", requerida: true },
    { rol: "profesional", etiqueta: "Profesional odontólogo", requerida: true },
  ],
  // A4 (595,3 × 841,9 pt), dos páginas, en Arial de 9 pt (7 pt el
  // diagnóstico, el plan y el consentimiento) con renglones de puntos. Medido
  // con scripts/medir-huecos.py; el odontograma, con
  // scripts/medir-odontograma.py sobre la imagen escaneada de la página 2.
  lamina: {
    paginas: [
      { ancho: 595.3, alto: 841.9 },
      { ancho: 595.3, alto: 841.9 },
    ],
    zonas: [
      // Encabezado.
      {
        id: "lugar",
        pagina: 1,
        x: 271.5,
        y: 95.8,
        ancho: 191.9,
        tamano: 9,
        texto: "{{lugar}}",
      },
      {
        id: "fecha_dia",
        pagina: 1,
        x: 492.5,
        y: 95.8,
        ancho: 16.5,
        tamano: 9,
        alinear: "centro",
        texto: "{{sistema.fecha:dia}}",
      },
      {
        id: "fecha_mes",
        pagina: 1,
        x: 512.5,
        y: 95.8,
        ancho: 15.5,
        tamano: 9,
        alinear: "centro",
        texto: "{{sistema.fecha:mes}}",
      },
      {
        id: "fecha_anio",
        pagina: 1,
        x: 533.5,
        y: 95.8,
        ancho: 22,
        tamano: 9,
        alinear: "centro",
        texto: "{{sistema.fecha:anio}}",
      },
      {
        id: "odontologo",
        pagina: 1,
        x: 97,
        y: 124.2,
        ancho: 355,
        texto: "{{odontologo}}",
      },
      // Cinco casillas de ancho desparejo (de 15,3 a 18 pt): el paso es el
      // promedio, y ningún carácter se corre más de 0,6 pt del centro de la suya.
      {
        id: "matricula",
        pagina: 1,
        x: 458.7,
        y: 132.9,
        ancho: 88.4,
        casillas: { cantidad: 5, paso: 17.68 },
        texto: "{{matricula}}",
      },
      {
        id: "paciente_nombre",
        pagina: 1,
        x: 84,
        y: 166,
        ancho: 200,
        texto: "{{paciente_nombre}}",
      },
      // Dieciséis casillas que alternan 12,2 y 15,7 pt: el paso minimiza el
      // corrimiento más grande (2,1 pt, dentro de la casilla).
      {
        id: "afiliado",
        pagina: 1,
        x: 321.27,
        y: 170.5,
        ancho: 226.56,
        casillas: { cantidad: 16, paso: 14.16 },
        texto: "{{afiliado}}",
      },
      {
        id: "obra_social",
        pagina: 1,
        x: 63.7,
        y: 196.7,
        ancho: 302,
        tamano: 9,
        texto: "{{obra_social}}",
      },
      {
        id: "fecha_nacimiento",
        pagina: 1,
        x: 387.4,
        y: 196.7,
        ancho: 61.8,
        tamano: 9,
        texto: "{{fecha_nacimiento}}",
      },
      {
        id: "telefono",
        pagina: 1,
        x: 463.6,
        y: 196.7,
        ancho: 92.7,
        tamano: 9,
        vacio: "—",
        texto: "{{telefono}}",
      },
      {
        id: "edad",
        pagina: 1,
        x: 46.8,
        y: 209.7,
        ancho: 35,
        tamano: 9,
        vacio: "—",
        texto: "{{edad}}",
      },
      {
        id: "estado_civil",
        pagina: 1,
        x: 126.9,
        y: 209.7,
        ancho: 82,
        tamano: 9,
        texto: "{{estado_civil}}",
      },
      {
        id: "nacionalidad",
        pagina: 1,
        x: 253.6,
        y: 209.7,
        ancho: 78.2,
        tamano: 9,
        texto: "{{nacionalidad}}",
      },
      {
        id: "dni",
        pagina: 1,
        x: 367.3,
        y: 209.7,
        ancho: 77.9,
        tamano: 9,
        texto: "{{dni}}",
      },
      {
        id: "celular",
        pagina: 1,
        x: 460.4,
        y: 209.7,
        ancho: 96.7,
        tamano: 9,
        texto: "{{celular}}",
      },
      {
        id: "domicilio",
        pagina: 1,
        x: 162.4,
        y: 222.5,
        ancho: 395.8,
        tamano: 9,
        texto: "{{domicilio}}",
      },
      {
        id: "profesion",
        pagina: 1,
        x: 92.8,
        y: 235.5,
        ancho: 139.5,
        tamano: 9,
        texto: "{{profesion}}",
      },
      {
        id: "titular",
        pagina: 1,
        x: 256.8,
        y: 235.5,
        ancho: 66,
        tamano: 9,
        vacio: "—",
        texto: "{{titular}}",
      },
      {
        id: "lugar_trabajo",
        pagina: 1,
        x: 378.6,
        y: 235.5,
        ancho: 96.4,
        tamano: 9,
        texto: "{{lugar_trabajo}}",
      },
      {
        id: "jerarquia",
        pagina: 1,
        x: 508.2,
        y: 235.5,
        ancho: 48.4,
        tamano: 9,
        minimo: 5,
        vacio: "—",
        texto: "{{jerarquia}}",
      },

      // Cuestionario, columna izquierda.
      ...izquierda("padre_vive", 1, 277.0),
      {
        id: "padre_enfermedad",
        pagina: 1,
        x: 36.4,
        y: 286.7,
        ancho: 246.6,
        sangria: 141.6,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{padre_enfermedad}}",
      },
      ...izquierda("madre_vive", 1, 310.4),
      {
        id: "madre_enfermedad",
        pagina: 1,
        x: 36.4,
        y: 320,
        ancho: 246.6,
        sangria: 141.6,
        lineas: 2,
        interlineado: 10.4,
        tamano: 9,
        texto: "{{madre_enfermedad}}",
      },
      ...izquierda("hermanos", 1, 343.7),
      {
        id: "hermanos_sanos",
        pagina: 1,
        x: 68,
        y: 353.3,
        ancho: 215.2,
        tamano: 9,
        texto: "{{hermanos_sanos}}",
      },
      ...izquierda("enfermedad", 1, 366.8),
      {
        id: "enfermedad_detalle",
        pagina: 1,
        x: 69,
        y: 376.4,
        ancho: 212.7,
        tamano: 9,
        texto: "{{enfermedad:detalle}}",
      },
      ...izquierda("tratamiento_medico", 1, 389.7),
      {
        id: "tratamiento_medico_detalle",
        pagina: 1,
        x: 60.5,
        y: 399.4,
        ancho: 222.7,
        tamano: 9,
        texto: "{{tratamiento_medico:detalle}}",
      },
      // El hueco de la pregunta (63 pt) es angosto: los dos renglones de abajo.
      {
        id: "medicamentos_habituales",
        pagina: 1,
        x: 36.4,
        y: 420.1,
        ancho: 246.6,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{medicamentos_habituales}}",
      },
      {
        id: "medicamentos_5_anios",
        pagina: 1,
        x: 36.4,
        y: 451.1,
        ancho: 243.5,
        lineas: 2,
        interlineado: 10.4,
        tamano: 9,
        texto: "{{medicamentos_5_anios}}",
      },
      ...izquierda("deporte", 1, 474.8),
      ...izquierda("deporte_malestar", 1, 487.5),
      ...izquierda("alergico", 1, 500.1),
      enHueco("alergias_anestesia", 1, 511.1, 91, 14, "{{alergias=anestesia}}"),
      enHueco(
        "alergias_penicilina",
        1,
        511.1,
        164.4,
        15.1,
        "{{alergias=penicilina}}",
      ),
      {
        id: "alergias_otras",
        pagina: 1,
        x: 202.9,
        y: 509.9,
        ancho: 77.8,
        tamano: 9,
        texto: "{{alergias_otras}}",
      },
      {
        id: "cicatrizacion",
        pagina: 1,
        x: 36.4,
        y: 530.5,
        ancho: 246.6,
        sangria: 64.6,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{cicatrizacion}}",
      },
      ...izquierda("colageno", 1, 554.3),
      ...izquierda("fiebre_reumatica", 1, 566.9),
      {
        id: "fiebre_reumatica_proteccion",
        pagina: 1,
        x: 179.9,
        y: 576.5,
        ancho: 102.9,
        tamano: 9,
        texto: "{{fiebre_reumatica_proteccion}}",
      },
      ...izquierda("diabetico", 1, 589.9),
      {
        id: "diabetes_controlada",
        pagina: 1,
        x: 104.9,
        y: 599.5,
        ancho: 16.5,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{diabetes_controlada}}",
      },
      {
        id: "diabetes_con_que",
        pagina: 1,
        x: 159.9,
        y: 599.5,
        ancho: 122.9,
        tamano: 9,
        texto: "{{diabetes_con_que}}",
      },
      ...izquierda("cardiaco", 1, 612.8),
      {
        id: "cardiaco_detalle",
        pagina: 1,
        x: 58,
        y: 622.6,
        ancho: 225.2,
        tamano: 9,
        texto: "{{cardiaco:detalle}}",
      },
      ...izquierda("aspirina", 1, 635.9),
      {
        id: "aspirina_detalle",
        pagina: 1,
        x: 117.4,
        y: 645.5,
        ancho: 167.8,
        tamano: 9,
        texto: "{{aspirina:detalle}}",
      },
      ...izquierda("presion_alta", 1, 658.9),
      ...izquierda("chagas", 1, 671.5),
      {
        id: "chagas_tratamiento",
        pagina: 1,
        x: 120.9,
        y: 681.1,
        ancho: 160.3,
        tamano: 9,
        texto: "{{chagas_tratamiento}}",
      },
      ...izquierda("renales", 1, 694.6),
      ...izquierda("ulcera", 1, 707.2),
      ...izquierda("hepatitis", 1, 719.9),
      casilla("hepatitis_a", 1, 732.5, 96.0, "{{hepatitis_tipo=a}}"),
      casilla("hepatitis_b", 1, 732.5, 125.4, "{{hepatitis_tipo=b}}"),
      casilla("hepatitis_c", 1, 732.5, 152.8, "{{hepatitis_tipo=c}}"),
      ...izquierda("hepatico", 1, 745.1),
      {
        id: "hepatico_detalle",
        pagina: 1,
        x: 60.5,
        y: 754.8,
        ancho: 222.7,
        tamano: 9,
        texto: "{{hepatico:detalle}}",
      },
      ...izquierda("convulsiones", 1, 768.1),
      ...izquierda("epileptico", 1, 780.7),
      {
        id: "epileptico_detalle",
        pagina: 1,
        x: 122,
        y: 790.5,
        ancho: 161.7,
        tamano: 9,
        texto: "{{epileptico:detalle}}",
      },
      ...izquierda("sifilis", 1, 803.8),

      // Cuestionario, columna derecha.
      ...derecha("infecto", 261.5),
      ...derecha("transfusiones", 274.1),
      ...derecha("operado", 286.8),
      {
        id: "operado_detalle",
        pagina: 1,
        x: 341.5,
        y: 296.4,
        ancho: 212.7,
        tamano: 9,
        texto: "{{operado:detalle}}",
      },
      {
        id: "operado_cuando",
        pagina: 1,
        x: 345.5,
        y: 306.9,
        ancho: 207.8,
        tamano: 9,
        texto: "{{operado_cuando}}",
      },
      ...derecha("respiratorio", 320.2),
      {
        id: "respiratorio_detalle",
        pagina: 1,
        x: 333,
        y: 329.8,
        ancho: 232.8,
        tamano: 9,
        texto: "{{respiratorio:detalle}}",
      },
      ...derecha("fuma", 343.1),
      ...derecha("embarazada", 355.9),
      {
        id: "embarazada_detalle",
        pagina: 1,
        x: 392,
        y: 365.5,
        ancho: 172.9,
        tamano: 9,
        texto: "{{embarazada:detalle}}",
      },
      ...derecha("otra_enfermedad", 389.2),
      {
        id: "otra_enfermedad_detalle",
        pagina: 1,
        x: 308.9,
        y: 398.8,
        ancho: 256.7,
        sangria: 21.6,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{otra_enfermedad:detalle}}",
      },
      {
        id: "homeopatia",
        pagina: 1,
        x: 308.9,
        y: 429.9,
        ancho: 261.5,
        tamano: 9,
        texto: "{{homeopatia}}",
      },
      {
        id: "medico_clinico",
        pagina: 1,
        x: 371,
        y: 440.2,
        ancho: 198.4,
        tamano: 9,
        texto: "{{medico_clinico}}",
      },
      // El hueco del título (61 pt) es angosto: el renglón entero de abajo.
      {
        id: "derivacion",
        pagina: 1,
        x: 308.9,
        y: 461,
        ancho: 261.5,
        tamano: 9,
        texto: "{{derivacion}}",
      },

      // Historia clínica odontológica.
      {
        id: "motivo_consulta",
        pagina: 1,
        x: 308.9,
        y: 508.1,
        ancho: 258.2,
        sangria: 117.5,
        lineas: 2,
        interlineado: 10.4,
        tamano: 9,
        texto: "{{motivo_consulta}}",
      },
      ...derechaAncha("consulto_otro", 1, 542.1),
      ...derechaAncha("tomo_medicamento", 1, 554.9),
      {
        id: "tomo_medicamento_detalle",
        pagina: 1,
        x: 308.9,
        y: 564.5,
        ancho: 257,
        sangria: 119.5,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{tomo_medicamento:detalle}}",
      },
      {
        id: "medicamento_desde",
        pagina: 1,
        x: 374.5,
        y: 585.2,
        ancho: 191.9,
        tamano: 9,
        texto: "{{medicamento_desde}}",
      },
      ...derechaAncha("medicamento_resultados", 1, 598.6),
      // "Ha tenido dolor? ☐": el papel tiene una sola casilla.
      casilla("dolor_si", 1, 611.2, 376.4, "{{dolor=si}}"),
      casilla("dolor_suave", 1, 611.2, 494.9, "{{dolor_tipo=suave}}"),
      casilla("dolor_moderado", 1, 611.2, 553.8, "{{dolor_tipo=moderado}}"),
      casilla("dolor_intenso", 1, 623.9, 339.9, "{{dolor_tipo=intenso}}"),
      casilla("dolor_temporario", 1, 623.9, 406.8, "{{dolor_tipo=temporario}}"),
      casilla(
        "dolor_intermitente",
        1,
        623.9,
        485.3,
        "{{dolor_tipo=intermitente}}",
      ),
      casilla("dolor_continuo", 1, 623.9, 556.2, "{{dolor_tipo=continuo}}"),
      casilla("dolor_espontaneo", 1, 636.5, 360.9, "{{dolor_tipo=espontaneo}}"),
      casilla("dolor_provocado", 1, 636.5, 439.9, "{{dolor_tipo=provocado}}"),
      casilla("dolor_al_frio", 1, 636.5, 491.9, "{{dolor_tipo=al_frio}}"),
      casilla("dolor_al_calor", 1, 636.5, 556.8, "{{dolor_tipo=al_calor}}"),
      casilla("dolor_localizado", 1, 649.1, 353.4, "{{dolor_tipo=localizado}}"),
      {
        id: "dolor_donde",
        pagina: 1,
        x: 420.4,
        y: 647.9,
        ancho: 149.5,
        tamano: 9,
        texto: "{{dolor_donde}}",
      },
      casilla("dolor_irradiado", 1, 661.8, 345.9, "{{dolor_tipo=irradiado}}"),
      {
        id: "dolor_hacia_donde",
        pagina: 1,
        x: 414.4,
        y: 660.6,
        ancho: 151.9,
        tamano: 9,
        texto: "{{dolor_hacia_donde}}",
      },
      {
        id: "dolor_calma",
        pagina: 1,
        x: 308.9,
        y: 671.4,
        ancho: 256,
        sangria: 106.5,
        lineas: 2,
        interlineado: 10.4,
        tamano: 9,
        texto: "{{dolor_calma}}",
      },
      ...derechaAncha("golpe", 1, 695.2),
      {
        id: "golpe_cuando",
        pagina: 1,
        x: 343.5,
        y: 704.8,
        ancho: 55.4,
        tamano: 9,
        texto: "{{golpe_cuando}}",
      },
      {
        id: "golpe_como",
        pagina: 1,
        x: 308.9,
        y: 704.8,
        ancho: 257.5,
        sangria: 168.5,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{golpe_como}}",
      },
      ...derechaAncha("fractura", 1, 728.5),
      {
        id: "fractura_detalle",
        pagina: 1,
        x: 330.5,
        y: 738.1,
        ancho: 85.5,
        tamano: 9,
        texto: "{{fractura:detalle}}",
      },
      // El hueco del título (45 pt) es angosto: los dos renglones de abajo.
      {
        id: "fractura_tratamiento",
        pagina: 1,
        x: 308.9,
        y: 748.5,
        ancho: 259,
        lineas: 2,
        interlineado: 10.4,
        tamano: 9,
        texto: "{{fractura_tratamiento}}",
      },
      {
        id: "dificultad_hablar",
        pagina: 1,
        x: 424.8,
        y: 769.2,
        ancho: 141.6,
        tamano: 9,
        texto: "{{dificultad_hablar}}",
      },
      {
        id: "dificultad_masticar",
        pagina: 1,
        x: 371,
        y: 779.5,
        ancho: 196.9,
        tamano: 9,
        texto: "{{dificultad_masticar}}",
      },
      {
        id: "dificultad_abrir",
        pagina: 1,
        x: 384,
        y: 789.9,
        ancho: 182.7,
        tamano: 9,
        texto: "{{dificultad_abrir}}",
      },
      {
        id: "dificultad_tragar",
        pagina: 1,
        x: 415.4,
        y: 800.3,
        ancho: 150.9,
        tamano: 9,
        texto: "{{dificultad_tragar}}",
      },

      // Página 2: lesiones.
      enHueco("anormal_labios", 2, 60.0, 206, 14, "{{anormal_en=labios}}"),
      enHueco("anormal_lengua", 2, 70.3, 70, 22.9, "{{anormal_en=lengua}}"),
      enHueco("anormal_paladar", 2, 70.3, 133, 18, "{{anormal_en=paladar}}"),
      enHueco(
        "anormal_piso_de_boca",
        2,
        70.3,
        209.5,
        14,
        "{{anormal_en=piso_de_boca}}",
      ),
      enHueco(
        "anormal_carrillos",
        2,
        80.7,
        74,
        17.5,
        "{{anormal_en=carrillos}}",
      ),
      enHueco(
        "anormal_rebordes",
        2,
        80.7,
        136.9,
        27.9,
        "{{anormal_en=rebordes}}",
      ),
      enHueco("anormal_trigono", 2, 80.7, 193, 27, "{{anormal_en=trigono}}"),
      enHueco(
        "anormal_retromolar",
        2,
        80.7,
        268.4,
        25.4,
        "{{anormal_en=retromolar}}",
      ),
      ...izquierda("manchas", 2, 103.2),
      ...izquierda("abultamiento", 2, 115.8),
      ...izquierda("ulceraciones", 2, 128.5),
      ...izquierda("ampollas", 2, 141.1),
      {
        id: "lesiones_otras",
        pagina: 2,
        x: 36.4,
        y: 150.9,
        ancho: 261.5,
        sangria: 27.1,
        lineas: 2,
        interlineado: 10.3,
        tamano: 9,
        texto: "{{lesiones_otras}}",
      },
      ...izquierda("encias_sangran", 2, 174.5),
      {
        id: "encias_sangran_detalle",
        pagina: 2,
        x: 73.4,
        y: 184.2,
        ancho: 220.4,
        tamano: 9,
        texto: "{{encias_sangran:detalle}}",
      },

      // Página 2: otros signos e higiene.
      ...derechaAncha("pus", 2, 61.8),
      {
        id: "pus_detalle",
        pagina: 2,
        x: 354,
        y: 71.4,
        ancho: 213.9,
        tamano: 9,
        texto: "{{pus:detalle}}",
      },
      ...derechaAncha("movilidad", 2, 84.9),
      {
        id: "dientes_altos",
        pagina: 2,
        x: 447.9,
        y: 94.5,
        ancho: 119.9,
        tamano: 9,
        texto: "{{dientes_altos}}",
      },
      ...derechaAncha("cara_hinchada", 2, 107.8),
      enHueco(
        "hinchazon_hielo",
        2,
        118.7,
        367.5,
        27.4,
        "{{hinchazon_aplico=hielo}}",
      ),
      enHueco(
        "hinchazon_calor",
        2,
        118.7,
        419.5,
        27.4,
        "{{hinchazon_aplico=calor}}",
      ),
      {
        id: "hinchazon_otros",
        pagina: 2,
        x: 475.4,
        y: 117.5,
        ancho: 92,
        tamano: 9,
        texto: "{{hinchazon_otros}}",
      },
      {
        id: "momentos_azucar",
        pagina: 2,
        x: 420,
        y: 127.8,
        ancho: 146.9,
        tamano: 9,
        texto: "{{momentos_azucar}}",
      },
      {
        id: "indice_placa",
        pagina: 2,
        x: 371.9,
        y: 138.1,
        ancho: 194.5,
        tamano: 9,
        texto: "{{indice_placa}}",
      },
      casilla("higiene_muy_bueno", 2, 172.2, 354.9, "{{higiene=muy_bueno}}"),
      casilla("higiene_bueno", 2, 172.2, 401.9, "{{higiene=bueno}}"),
      casilla("higiene_deficiente", 2, 172.2, 462.7, "{{higiene=deficiente}}"),
      casilla("higiene_malo", 2, 172.2, 503.2, "{{higiene=malo}}"),

      // Estado bucal general.
      ...siNo("sarro", 2, 452.2, 218.2, 250.1),
      ...siNo("periodontal", 2, 452.2, 401.6, 433.4),

      // Diagnóstico, plan y observaciones: cuatro renglones de puntos a 7 pt.
      {
        id: "diagnostico",
        pagina: 2,
        x: 32.1,
        y: 484.8,
        ancho: 409.7,
        lineas: 4,
        interlineado: 9.67,
        tamano: 8,
        minimo: 5,
        texto: "{{diagnostico}}",
      },
      {
        id: "diagnostico_anexo",
        pagina: 2,
        x: 543.4,
        y: 523.4,
        ancho: 20,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{diagnostico_anexo}}",
      },
      {
        id: "plan_fecha_dia",
        pagina: 2,
        x: 125.3,
        y: 542.7,
        ancho: 13,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{plan_fecha:dia}}",
      },
      {
        id: "plan_fecha_mes",
        pagina: 2,
        x: 141.3,
        y: 542.7,
        ancho: 13,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{plan_fecha:mes}}",
      },
      {
        id: "plan_fecha_anio",
        pagina: 2,
        x: 157,
        y: 542.7,
        ancho: 18,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{plan_fecha:anio}}",
      },
      {
        id: "plan",
        pagina: 2,
        x: 32.1,
        y: 552.5,
        ancho: 409.7,
        lineas: 4,
        interlineado: 9.63,
        tamano: 8,
        minimo: 5,
        texto: "{{plan}}",
      },
      {
        id: "plan_anexo",
        pagina: 2,
        x: 543.4,
        y: 591.1,
        ancho: 20,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{plan_anexo}}",
      },
      {
        id: "observaciones",
        pagina: 2,
        x: 32.1,
        y: 610.4,
        ancho: 409.7,
        lineas: 4,
        interlineado: 9.67,
        tamano: 8,
        minimo: 5,
        texto: "{{observaciones}}",
      },
      {
        id: "observaciones_anexo",
        pagina: 2,
        x: 543.4,
        y: 649.1,
        ancho: 20,
        tamano: 8,
        alinear: "centro",
        vacio: "—",
        texto: "{{observaciones_anexo}}",
      },

      // Consentimiento.
      {
        id: "suscribe_nombre",
        pagina: 2,
        x: 91.1,
        y: 682.8,
        ancho: 124.8,
        tamano: 8,
        texto: "{{suscribe_nombre}}",
      },
      {
        id: "suscribe_dni",
        pagina: 2,
        x: 239.5,
        y: 682.8,
        ancho: 97.9,
        tamano: 8,
        texto: "{{suscribe_dni}}",
      },
      {
        id: "suscribe_domicilio",
        pagina: 2,
        x: 407.9,
        y: 682.8,
        ancho: 150.7,
        tamano: 8,
        texto: "{{suscribe_domicilio}}",
      },
      // "…propuesta por el/la Dr/a MP……": el nombre y la matrícula.
      {
        id: "consiente_profesional",
        pagina: 2,
        x: 428.3,
        y: 698.9,
        ancho: 131,
        tamano: 8,
        texto: "{{odontologo}}, {{matricula}}",
      },
      // Debajo de la firma: "aclaración" y "DNI Nº" de quien suscribe.
      {
        id: "aclaracion",
        pagina: 2,
        x: 242.1,
        y: 756.4,
        ancho: 135.4,
        tamano: 9,
        alinear: "centro",
        texto: "{{suscribe_nombre}}",
      },
      {
        id: "aclaracion_dni",
        pagina: 2,
        x: 443.8,
        y: 756.4,
        ancho: 110.9,
        tamano: 9,
        alinear: "centro",
        texto: "{{suscribe_dni}}",
      },
      // El papel no tiene renglón para la firma del profesional: su rótulo,
      // en el margen de abajo, debajo de su lugar.
      {
        id: "rotulo_firma_profesional",
        pagina: 2,
        x: 400,
        y: 820,
        ancho: 156,
        tamano: 8,
        alinear: "centro",
        texto: "Firma del profesional",
      },
    ],
    firmas: [
      { rol: "paciente", pagina: 2, x: 31, y: 756, ancho: 143, alto: 40 },
      { rol: "profesional", pagina: 2, x: 400, y: 811, ancho: 156, alto: 32 },
    ],
    odontogramas: [
      {
        campo: "odontograma",
        pagina: 2,
        piezas: [
          { pieza: "18", x: 33.77, y: 283.99, lado: 18.13 },
          { pieza: "17", x: 54.54, y: 284.11, lado: 18.13 },
          { pieza: "16", x: 75.37, y: 284.41, lado: 18.01 },
          { pieza: "15", x: 96.14, y: 284.29, lado: 18.25 },
          { pieza: "14", x: 117.04, y: 284.05, lado: 18.49 },
          { pieza: "13", x: 138.23, y: 284.47, lado: 18.13 },
          { pieza: "12", x: 159.06, y: 284.53, lado: 18.01 },
          { pieza: "11", x: 180.01, y: 284.47, lado: 18.13 },
          { pieza: "21", x: 209.54, y: 284.47, lado: 18.37 },
          { pieza: "22", x: 230.91, y: 284.71, lado: 18.13 },
          { pieza: "23", x: 252.04, y: 284.71, lado: 18.13 },
          { pieza: "24", x: 272.81, y: 284.83, lado: 18.13 },
          { pieza: "25", x: 293.52, y: 284.77, lado: 18.25 },
          { pieza: "26", x: 314.41, y: 285.01, lado: 18.01 },
          { pieza: "27", x: 335.36, y: 284.47, lado: 18.13 },
          { pieza: "28", x: 355.77, y: 284.47, lado: 18.13 },
          { pieza: "48", x: 34.37, y: 310.77, lado: 18.13 },
          { pieza: "47", x: 55.08, y: 310.95, lado: 18.01 },
          { pieza: "46", x: 76.1, y: 311.07, lado: 18.01 },
          { pieza: "45", x: 96.93, y: 311.13, lado: 18.13 },
          { pieza: "44", x: 118.06, y: 311.13, lado: 18.13 },
          { pieza: "43", x: 138.95, y: 311.13, lado: 18.13 },
          { pieza: "42", x: 159.84, y: 311.37, lado: 17.89 },
          { pieza: "41", x: 180.73, y: 311.37, lado: 18.13 },
          { pieza: "31", x: 209.6, y: 311.31, lado: 18.25 },
          { pieza: "32", x: 230.67, y: 311.13, lado: 18.37 },
          { pieza: "33", x: 251.8, y: 311.62, lado: 18.13 },
          { pieza: "34", x: 272.87, y: 311.68, lado: 18.01 },
          { pieza: "35", x: 293.58, y: 311.62, lado: 18.13 },
          { pieza: "36", x: 314.41, y: 311.68, lado: 18.01 },
          { pieza: "37", x: 335.6, y: 311.86, lado: 18.13 },
          { pieza: "38", x: 355.95, y: 311.68, lado: 18.25 },
          { pieza: "55", x: 96.99, y: 361.52, lado: 18.49 },
          { pieza: "54", x: 118.24, y: 361.4, lado: 18.25 },
          { pieza: "53", x: 139.37, y: 361.64, lado: 18.01 },
          { pieza: "52", x: 160.02, y: 361.64, lado: 18.25 },
          { pieza: "51", x: 180.97, y: 361.58, lado: 18.37 },
          { pieza: "61", x: 209.24, y: 361.88, lado: 18.25 },
          { pieza: "62", x: 230.43, y: 361.82, lado: 18.37 },
          { pieza: "63", x: 251.56, y: 361.82, lado: 18.37 },
          { pieza: "64", x: 272.63, y: 362.12, lado: 18.01 },
          { pieza: "65", x: 293.4, y: 362.24, lado: 18.01 },
          { pieza: "85", x: 96.39, y: 388.55, lado: 18.25 },
          { pieza: "84", x: 117.46, y: 388.61, lado: 18.37 },
          { pieza: "83", x: 138.47, y: 388.73, lado: 18.13 },
          { pieza: "82", x: 159.36, y: 388.97, lado: 18.13 },
          { pieza: "81", x: 180.25, y: 388.97, lado: 18.13 },
          { pieza: "71", x: 209.54, y: 389.21, lado: 18.13 },
          { pieza: "72", x: 230.49, y: 389.15, lado: 18.25 },
          { pieza: "73", x: 251.56, y: 389.45, lado: 18.13 },
          { pieza: "74", x: 272.57, y: 389.33, lado: 18.13 },
          { pieza: "75", x: 293.34, y: 389.45, lado: 18.13 },
        ],
        // La caja de "CANTIDAD DE DIENTES EXISTENTES" de las referencias.
        existentes: { x: 509.5, y: 404.8, ancho: 29.8, tamano: 10 },
      },
    ],
  },
};
